### PR TITLE
Remove googleapis-common-protos pin

### PR DESCRIPTION
**Pull request by apmorton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by apmorton** [comment]
For some reason this pin seems to be causing the following in our environment:
```
The following packages are incompatible
├─ dagster-gcp >=0.21.7,<1  is installable and it requires
│  └─ googleapis-common-protos !=1.57.0 *_1, which can be installed;
└─ googleapis-common-protos >=1.61.0  is not installable because it conflicts with any installable versions previously reported.
```

and the referenced fix has been merged a long time ago anyway.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Often a yak shave with the big FAANG packages as deps, buh: thanks for digging into this.

**Pull request merged**
